**Problem for this assignment.** <br>
To assess the financial statement of organization X. <br>

given - You have two list of data: monthly revenue and monthly expenses (for same financial year) <br>

Your goal:  <br>
1. profit for each month
2. profit after tax for each month (PAT) 
note: the tax rate is 30% <br>
3. profit margin for each month (PAT/REVENUE)
4. good months (PAT > PROFIT MEAN OF THE YEAR)
5. Bad months (PAT < PROFIT MEAN OF THE YEAR)
6. the best month (PAT is max for the year)
7. the worst month (PAT is min for the year)

All results need to be presented as list.


Round all values to two decimal point. All values will be in $1000.

Profit margin ratio must have no decimal point and should be in %.


In [16]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [17]:
len(revenue)

12

In [18]:
len(expenses)

12

In [19]:
#profit = revenue - expenses
#can I do vector operations like I did in R
#let's see
#not possible
#Why not convert it into an array
import numpy as np
type(revenue)
type(expenses)
Rev = np.array(revenue)
Exp = np.array(expenses)
print(Rev)
print(Exp)
type(Rev)
type(Exp)

[14574.49  7606.46  8611.41  9175.41  8058.65  8105.44 11496.28  9766.09
 10305.32 14379.96 10713.97 15433.5 ]
[12051.82  5695.07 12319.2  12089.72  8658.57   840.2   3285.73  5821.12
  6976.93 16618.61 10054.37  3803.96]


numpy.ndarray

In [20]:
#applying vector operations on arrays
Profit = Rev-Exp
#damn
Profit  #this will be profit for each month
#but we will have to convert it back to list ...?? how to ??
#do it in the end

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [21]:
#profit after tax = profit * tax rate 
tax_rate = 0.3
PAT = Profit * (1-tax_rate) 
PAT
#This is your second result

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [22]:
#profit margin for each month (PAT/ revenue)
Profit_margin = PAT/Rev
Profit_margin
#This is going to be your third answer

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [23]:
import math
math.floor(Margin.round(2) *100)

NameError: name 'Margin' is not defined

In [24]:
int(55.555555)  #using int() to convert a float type to integer
#But... int() can only be used for single number. Nor for array
math.floor(45.780980980492381984) #same as int() 

45

In [25]:
#finding the good months
#good months (PAT > PROFIT MEAN OF THE YEAR)
#This looks like a condition 
#apply if statement for it
#But before you do that ... you must know the mean

#to calculate mean ... let's use dot and tab. it is an array.. cool idea
#do we need to find mean of the profit?
#or 
#mean of the PAT?
#since we are comparing PAT of a month with the mean of the year. Mean must be of PAT.
#comparing like things is common sense.
#OK
PAT_mean = PAT.mean()
PAT_mean

1750.6813333333332

In [26]:
PAT

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [27]:
PAT_mean

1750.6813333333332

In [28]:
PAT[0]

1765.869

In [29]:
#let's apply if statements now
#wait ... what if you can apply else if for this ... calcualte good months, bad months together
#ok
#if PAT.any() > PAT_mean:
#    print("Good Month")
#Since you need to check each individual value with PAT_mean. apply for loop
for i in range(len(PAT)):
    if PAT[i] > PAT_mean:
        print(i+1, " ", "="," ",PAT[i])
#do test run first   
#it works
#do the same but separately for bad months

1   =   1765.869
6   =   5085.668
7   =   5747.385
8   =   2761.479
9   =   2329.8729999999996
12   =   8140.678


In [30]:
Good_months = np.array([0]*12)
for i in range(len(PAT)):
    if PAT[i] > PAT_mean:
        Good_months[i] = PAT[i].round(2)
        print(i+1, " ", "="," ",PAT[i].round(2))

print(Good_months)
type(Good_months)

1   =   1765.87
6   =   5085.67
7   =   5747.38
8   =   2761.48
9   =   2329.87
12   =   8140.68
[1765    0    0    0    0 5085 5747 2761 2329    0    0 8140]


numpy.ndarray

In [31]:
for i in range(len(PAT)):
    if PAT[i] < PAT_mean:
        print(i+1, " ", "="," ",round(PAT[i],2))
#you need to store these values into an object.
#ok
#initialisation concept
#try in another cell

2   =   1337.97
3   =   -2595.45
4   =   -2040.02
5   =   -419.94
10   =   -1567.06
11   =   461.72


In [32]:
Bad_months = np.array([0]*12)
for i in range(len(PAT)):
    if PAT[i] < PAT_mean:
        Bad_months[i] = PAT[i].round(2)
        print(i+1, " ", "="," ",PAT[i].round(2))

print(Bad_months)
type(Bad_months)

2   =   1337.97
3   =   -2595.45
4   =   -2040.02
5   =   -419.94
10   =   -1567.06
11   =   461.72
[    0  1337 -2595 -2040  -419     0     0     0     0 -1567   461     0]


numpy.ndarray

In [33]:
#the best month (PAT is max for the year)
#for this ... you don't need to use loops or if 
#Why
#we have dot and tab ... array non-sense
PAT_max = PAT.max()
Best_month = PAT_max
Best_month

8140.678

In [34]:
#the worst month (PAT is min for the year)
PAT_min = PAT.min()
Worst_month=PAT_min
Worst_month

-2595.4530000000004

In [35]:
#We need to get the decimal point right
#storing the values in to a list
Fin_Analysis = [Profit.round(2),PAT.round(2),Profit_margin.round(2),Good_months,Bad_months,Best_month.round(2),Worst_month.round(2)]

In [36]:
Fin_Analysis

[array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
         8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54]),
 array([ 1765.87,  1337.97, -2595.45, -2040.02,  -419.94,  5085.67,
         5747.38,  2761.48,  2329.87, -1567.06,   461.72,  8140.68]),
 array([ 0.12,  0.18, -0.3 , -0.22, -0.05,  0.63,  0.5 ,  0.28,  0.23,
        -0.11,  0.04,  0.53]),
 array([1765,    0,    0,    0,    0, 5085, 5747, 2761, 2329,    0,    0,
        8140]),
 array([    0,  1337, -2595, -2040,  -419,     0,     0,     0,     0,
        -1567,   461,     0]),
 8140.68,
 -2595.45]

**initialisation of arrays** <br>

Let's say you are working with a loop.  <br>
And, you need to store the result in a variable (an object). <br>
For that, you would need to use initialisation. <br>

Think of initialisation as creating an empty shell in which you put your result. But this empty shell must be of same length in order for it to house all the result values in it.  <br>

Below is the code that I created... pay attention to initialisation <br>
```python
Good_months = np.array([0]*12)  #This creates an empty array of length 12
for i in range(len(PAT)):
    if PAT[i] > PAT_mean:
        Good_months[i] = PAT[i].round(2)
        print(i+1, " ", "="," ",PAT[i].round(2))

print(Good_months)
type(Good_months)
```
In Python, a List can be treated as an Array.  <br>

So, when you need to create an empty array, create an empty list instead.  <br>

So, $[0]$ is an empty list and $[0]*12$ is an empty list of length 12.  <br>

I am attaching an image of an article that helped in doing that code- <br>
<img src="empty_list.png" width="750" height="400" />

In [2]:
a = list(range(1,4))
a

[1, 2, 3]

In [4]:
b = list(range(4,7))
b.

[4, 5, 6]

In [8]:
#operations with these two list

#initialisation (creating an empty list object)
x = []
for i in range(0,len(a)):
    x.append(a[i]*b[i]) #array.append() will add values to an array 
print(x)


[4, 10, 18]


In [7]:
#list comprehensions
#list comprehensions provide a concise way to create lists
#common applications are to make new lists where each element is the result of some operations applied to 
#each member of another sequence or iterable, or to create a subsequence of these elements that satisfy 
#a certain condition

a = list(range(1,4))
print(a)
#list comprehensions
y =[i * 2 for i in a]   #you are using square brackets
y

[1, 2, 3]


[2, 4, 6]

In [ ]:
#New functions
#round()
#max()
#min()


In [7]:
range(0,3)
list(range(3))

[0, 1, 2]

In [ ]:
range(5) #i am specifying the stop and by default the start = 0

In [47]:
#practice .append() method. It is used to add something in the end. Just like an appendix.
#append() increases the length by 1. 
a = [1,2,3]
b = [3]
a.append(b)
print(a)     #append() doesnot create a new list, instead it adds a single element to the existing list.

[1, 2, 3, [3]]


In [46]:
my_list = ['geeks', 'for', 'geeks']
another_list = [6, 0, 4, 1]
my_list.append(another_list)
print (my_list)

['geeks', 'for', 'geeks', [6, 0, 4, 1]]


In [49]:
my_list.append(a)
print(my_list)
#note: it has added the entire list as a single list object 

['geeks', 'for', 'geeks', [6, 0, 4, 1], [1, 2, 3, [3]], [1, 2, 3, [3]]]


**List append() method in python** <br>

- .append() allows you to add a 'single new element' at the end of a list. <br>
- This increases the length of your list to be increased by 1. <br>
 **Syntax:** <br>
list(to which you want to add to) . append(elements that you wish to add) <br>

Below are some of the examples:- <br>
```python
sample1 = ["Hello", "sir", 1,2,3,4,8]
sample1.append(10) #i am additional a list of single element to sample1
#see if new element as been added
print(sample1)
sample1 = ['Hello', 'sir', 1, 2, 3, 4, 8, 10] #10 has been added
#check its length
len(sample1) = 8
#-----------------------------------
#append method will only increase the length of a list by 1
sample2 = [50.45,56,78.90,48,3]
sample1.append(sample2)
print(sample1)
sample1 = ['Hello', 'sir', 1, 2, 3, 4, 8, 10, [50.45, 56, 78.9, 48, 3]]
#check the length after using append 
len(sample1) = 9  #note: length is just increased by 1
#------------------------------------
#let's add sample 1 to sample2 
sample2.append(sample1)
print(sample2)
sample2 = [50.45, 56, 78.9, 48, 3, ['Hello', 'sir', 1, 2, 3, 4, 8, 10, [...]]]
```

#how to use append method for loops  <br>
```python
x = []  #i have created an empty list
a = [1,2,3]
b = [5,6,7] 
for i in range(len(a)):    #range(len(a)) is very similar to saying range(3) as length of a is 3
    x.append(a[i] * b[i]) 

print(x)
#result : [5, 12, 21]
```

In [4]:
sample1 = ["Hello", "sir", 1,2,3,4,8]
sample1.append(10) #i am additional a single element to sample1
sample1
#.append will only increase the length of a list by 1
sample2 = [50.45,56,78.90,48,3]
sample1.append(sample2)
print(sample1)
len(sample1)

['Hello', 'sir', 1, 2, 3, 4, 8, 10, [50.45, 56, 78.9, 48, 3]]


9

In [2]:
sample1 = ["Hello", "sir", 1,2,3,4,8]
sample1.append(10) #i am additional a single element to sample1
sample1
print(len(sample1))

8


In [5]:
sample2.append(sample1)
print(sample2)

[50.45, 56, 78.9, 48, 3, ['Hello', 'sir', 1, 2, 3, 4, 8, 10, [...]]]


In [6]:
x = []  #i have created an empty list
a = [1,2,3]
b = [5,6,7] 
for i in range(len(a)):    #range(len(a)) is very similar to saying range(3) as length of a is 3
    x.append(a[i] * b[i]) 

print(x)

[5, 12, 21]


**List comprehension** <br>

 **Syntax : newList = [ expression(element) ```for``` element ```in``` oldList ```if condition``` ]**  <br>
 
<u> - it is short and simple way to create a new list from an existing list when you are working with loops and if statements.</u>  <br>
 Note: you must place the syntax in square bracket; [ ]  <br>
 
 let's see the examples to better understand it-  <br>
 ```python
a = [1,2,3]
newList = [i for i in a]
print(newList)
#result-
#newlist = [1, 2, 3]
```

```python
newlist2 =[i for i in range(15) if i % 2 == 0]
print(newlist2)
#result
# newlist2 = [0, 2, 4, 6, 8, 10, 12, 14]
```

```python
a = list(range(1,4))
print(a) = [1, 2, 3]
#list comprehensions
y =[i * 2 for i in a]   #you are using square brackets
y
#result
y = [2, 4, 6]
```

In [8]:
a = [1,2,3]
newList = [i for i in a]
print(newList)

[1, 2, 3]


In [12]:
newlist2 =[i for i in range(15) if i % 2 == 0]
print(newlist2)

[0, 2, 4, 6, 8, 10, 12, 14]
